from .lexing import token

token("space", r"(\s|;|,)*")
token("comment", r"--[^\n\r]*")
token("string", r"'[^']*'")
token("template-string", r'"[^"]*"')
token("float", r"-?\d*\.\d+([eE][-+]?\d+)?\b")
token("int", r"-?\d+\b")
token("name", r"[a-z]\w*")
token("concept", r"[A-Z]\w*")
token("!=")
token("!")
token("@")
token("$")
token("#")
token("%:")
token("%")
token("?:")
token("?")
token("/")
token(".")
token("..")
token(":")
token("=")
token("><")
token(">=")
token(">")
token("<>")
token("<=")
token("<")
token("*")
token("(")
token(")")
token("{")
token("}")
token("[")
token("]")
